mssc-beer-service:
  config:
    api:
      host: http://localhost:8089
      getBeerByIdPath: /api/v1/beer/{uuid}
      saveBeerPath: /api/v1/beer
      updateBeerPath: /api/v1/beer/{uuid}
      deleteBeerPath: /api/v1/beer/{uuid}
      getCustomerByIdPath: /api/v1/customer/{uuid}
      saveCustomerPath: /api/v1/customer
      updateCustomerPath: /api/v1/customer/{uuid}
      deleteCustomerPath: /api/v1/customer/{uuid}
    blocking-rest-template:
      maxTotal: 100
      socketTimeout: 3000
      connectionRequestTimeout: 3000
      defaultMaxPerRoute: 20


logging:
  level:
    org.apache.http: DEBUG
    com.example.demo: DEBUG

server:
  port: 8090
